/**
 * Import scraped YouTube transcripts into scenario format.
 * Reads JSONL from ytscraper output and creates scenario entries.
 *
 * Usage: npx tsx scripts/import-transcripts.ts
 */
import { readFileSync, writeFileSync, readdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const SCRAPER_OUTPUT = join(__dirname, '../../ytscraper/output')
const SCENARIO_OUTPUT = join(__dirname, '../src/lib/imported-scenarios.ts')

type Chunk = {
  source_video_id: string
  source_title: string
  source_channel: string
  source_url: string
  chunk_index: number
  start_time: number
  end_time: number
  text: string
  word_count: number
}

type ScenarioEntry = {
  speaker: string
  text: string
  delay: number
}

function cleanText(raw: string): string {
  // Remove duplicate lines from auto-captions
  const lines = raw.split('\n')
  const seen = new Set<string>()
  const deduped: string[] = []
  for (const line of lines) {
    const trimmed = line.trim()
    if (trimmed && !seen.has(trimmed)) {
      seen.add(trimmed)
      deduped.push(trimmed)
    }
  }
  return deduped.join(' ').replace(/\s+/g, ' ').trim()
}

function chunkToEntries(chunk: Chunk, startDelay: number): ScenarioEntry[] {
  const text = cleanText(chunk.text)
  // Split on sentence boundaries — roughly one entry per sentence or two
  const sentences = text.match(/[^.!?]+[.!?]+/g) ?? [text]

  const entries: ScenarioEntry[] = []
  let delay = startDelay

  for (const sentence of sentences) {
    const trimmed = sentence.trim()
    if (trimmed.length < 10) continue // skip tiny fragments

    entries.push({
      speaker: 'Table',
      text: trimmed,
      delay,
    })
    delay += 3 + Math.floor(trimmed.length / 30) // ~3-6 seconds per entry
  }

  return entries
}

function detectSystem(title: string, channel: string): string {
  const lower = (title + ' ' + channel).toLowerCase()
  if (lower.includes('critical role') || lower.includes('mighty nein')) return 'D&D 5e'
  if (lower.includes('dimension 20') || lower.includes('fantasy high')) return 'D&D 5e'
  if (lower.includes('pathfinder') || lower.includes('pf2e')) return 'Pathfinder 2e'
  if (lower.includes('call of cthulhu') || lower.includes('cthulhu')) return 'Call of Cthulhu'
  if (lower.includes('blades in the dark') || lower.includes('forged in the dark')) return 'Blades in the Dark'
  if (lower.includes('monster of the week')) return 'Monster of the Week'
  if (lower.includes('vampire') || lower.includes('masquerade')) return 'Vampire: The Masquerade'
  return 'TTRPG'
}

function main() {
  const files = readdirSync(SCRAPER_OUTPUT).filter(f => f.endsWith('.jsonl'))

  if (files.length === 0) {
    console.error('No JSONL files found in', SCRAPER_OUTPUT)
    process.exit(1)
  }

  const scenarios: string[] = []

  for (const file of files) {
    const path = join(SCRAPER_OUTPUT, file)
    const lines = readFileSync(path, 'utf-8').trim().split('\n')
    const chunks: Chunk[] = lines.map(l => JSON.parse(l))

    if (chunks.length === 0) continue

    const meta = chunks[0]
    const system = detectSystem(meta.source_title, meta.source_channel)
    const id = file.replace('.jsonl', '')

    // Take chunks 5-25 (skip intros, get the meat)
    const goodChunks = chunks.slice(5, Math.min(25, chunks.length))

    let allEntries: ScenarioEntry[] = []
    let delay = 0
    for (const chunk of goodChunks) {
      const entries = chunkToEntries(chunk, delay)
      allEntries = allEntries.concat(entries)
      delay = entries.length > 0 ? entries[entries.length - 1].delay + 4 : delay + 10
    }

    // Cap at ~150 entries for manageability
    allEntries = allEntries.slice(0, 150)

    console.log(`${id}: ${meta.source_title}`)
    console.log(`  System: ${system} | Chunks: ${goodChunks.length} | Entries: ${allEntries.length}`)

    scenarios.push(`  {
    id: '${id}',
    name: '${meta.source_title.replace(/'/g, "\\'")}',
    description: '${meta.source_channel.replace(/'/g, "\\'")} — ${system}',
    system: '${system}',
    context: 'System: ${system}. Source: ${meta.source_channel.replace(/'/g, "\\'")}. Auto-imported from YouTube captions.',
    backstories: '',
    entries: ${JSON.stringify(allEntries, null, 6).split('\n').map((l, i) => i === 0 ? l : '    ' + l).join('\n')},
  }`)
  }

  const output = `/**
 * Auto-imported scenarios from YouTube actual play transcripts.
 * Generated by scripts/import-transcripts.ts
 * Source: ytscraper output
 */
import type { Scenario } from './scenarios'

export const IMPORTED_SCENARIOS: Scenario[] = [
${scenarios.join(',\n')}
]
`

  writeFileSync(SCENARIO_OUTPUT, output)
  console.log(`\nWrote ${scenarios.length} scenarios to ${SCENARIO_OUTPUT}`)
}

main()
